### PR TITLE
#157751980 Develop user request form

### PR DESCRIPTION
**Pull request by asamisellah**
#### What does this PR do?
Implements a page where users can make a repair and maintenance requests through a form

#### Description of Task to be completed?
Create a form with the following input fields:
- request title
- service type i.e maintenance or repair
- description of the problem
- area where the service is required i.e. building/location
- category i.e. electrical, plumbing, automotive, floor/wall/ceiling

#### How should this be manually tested?
1. clone the [repo](https://github.com/asamisellah/Maintenance-Tracker)
2. open the folder in your text editor or IDE
3. `git chechout -b new-branch`
4. `git fetch ft-user-make-request-157751980`
5. open `ft-user-make-request-157751980` in your browser

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#157751980](https://www.pivotaltracker.com/story/show/157751980/comments/190009580)

#### Screenshots (if appropriate)
request-form

### CODE REVIEW

**Comment by gitaumoses4** [comment]
Well structured PR and use of commit naming guidelines. Great work.

**Comment by DennisWanjiru** [comment]
Good design. Great PR and follows guidelines

**Comment by blac-siren** [comment]
Good design. Well structured PR.

**Comment by janetnim** [comment]
You observed the guidelines and your PR is well written

**Pull request merged**
