### PR TITLE
#157746115 Create page for user to view all requests

### PR DESCRIPTION
**Pull request by asamisellah**
#### What does this PR do?
Implements a page where users can view all their repair and maintenance requests

#### Description of Task to be completed?
- Develop layout for the page which includes navigation bar
- Create a table to display the requests
- Include status badges to requests
- Include search field for quick search of the requests

#### How should this be manually tested?

1. clone the [repo](https://github.com/asamisellah/Maintenance-Tracker)
2. open the folder in your text editor or IDE
3. `git chechout -b new-branch`
4. `git fetch ft-user-all-requests-157746115`
5. run `user_all_requests.html` in your browser

#### Any background context you want to provide?
The following materials were helpful in building the page:
[Material design: the color system](https://material.io/design/color/#color-usage-palettes)
[Material icons](https://icomoon.io/app/#/select)
[Google fonts](https://fonts.google.com/)

#### What are the relevant pivotal tracker stories?
[#157746115](https://www.pivotaltracker.com/story/show/157746115/comments/189995596)

#### Screenshots (if appropriate)
user-all-request

### CODE REVIEW

**Comment by lawrenceChege** [comment]
I love your UI design!. 
it looks great especially the status buttons.
great detail in Pr and commits too

**Comment by blac-siren** [comment]
Great UI :+1: 
 but i think you might have made a mistake naming your PR.

**Comment by blac-siren** [comment]
Great :+1:

**Comment by blac-siren** [comment]
is it responsive.

**Comment by asamisellah** [comment]
@blac-siren I have not yet made it responsive. I hope to work on that soon

**Comment by asamisellah** [comment]
@lawrenceChege Thank you. If there's anything else I can improve on, let me.

**Comment by gtsofa** [comment]
Looks nice

**Comment by joelmachango** [comment]
@asamisellah Beautiful UI and the PR is well structured

**Comment by artorious** [comment]
Great design and PR presentation

**Comment by Slinjez** [comment]
The UI is great, nice pr... but I'm not sure we are allowed to change the name of the application.

**Comment by PromasterGuru** [comment]
Great and detailed UI

**Comment by alovega** [comment]
wow it looks great

**Pull request merged**
