### PR TITLE
#157746015 Develop Admin page to view  request details

### PR DESCRIPTION
**Pull request by asamisellah**
#### What does this PR do?
Implements a page where the admin can view details of a request. The admin can also approve, disapprove or resolve a request from the same page.

#### Description of tasks to be completed?
- Create a page to display details of the request
- Add buttons for approving or rejecting a request
- Add a button to resolve a request

#### How should this be manually tested?
1. clone the [repo](https://github.com/asamisellah/Maintenance-Tracker)
2. open the folder in your text editor or IDE
3. `git chechout -b new-branch`
4. `git fetch ft-admin-request-details-157745894`
5. open `adminl-request-details.htlml` in your browser

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#157746015](https://www.pivotaltracker.com/story/show/157746015/comments/190014621)
[#157808960](https://www.pivotaltracker.com/story/show/157808960/comments/190014622)
[#157809021](https://www.pivotaltracker.com/story/show/157809021/comments/190014623)

### Screenshots (if appropriate)
admin-request-details

### CODE REVIEW

**Comment by lawrenceChege** [comment]
It looks  great. i love it

**Comment by dalaineme** [comment]
Yeah, it does look really good.

**Comment by joelmachango** [comment]
@asamisellah Beautiful UI!

**Comment by asamisellah** [comment]
I truly appreciate your reviews.

**Pull request merged**
